### ISSUE TITLE
App crashes when connection with miio device is broken

### ISSUE THREAD

**Issue by chrisboer** [jghaanstra/com.xiaomi-miio#32]
The log has been sent to the developer.

The unique log ID is: 663782b4-93a2-4c80-9c39-ad938327f921

**Comment by jghaanstra** [comment]
Full error log.

```
---- stdout ----
2018-05-26 13:30:06 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...

---- stderr ----
(node:2369) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: reject is not defined
(node:2369) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/drivers/mi-robot/device.js:25
      this.miio.clean()
                ^

TypeError: Cannot read property 'clean' of undefined
    at MiRobotDevice.onCapabilityOnoff (/drivers/mi-robot/device.js:25:17)
    at MiRobotDevice.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:1928)
    at emitTwo (events.js:126:13)
    at MiRobotDevice.emit (events.js:214:7)
    at MiRobotDriver.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:1505)
    at emitTwo (events.js:126:13)
    at MiRobotDriver.emit (events.js:214:7)
    at Homey.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:1461)
    at SDK._onReady (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:993)
    at ManagerDrivers._onEventDriverMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:1380)
```
  
It looks like the connection between Homey and your vacuum cleaner is broken. This might be due to unstable WiFi or the Mi Robot going into sleep mode. When this happens this is not handle correctly within my app because I dont know how the properly handle these exceptions due to my limited coding skills. Small change this will be fixed any time shortly.

**Comment by chrisboer** [comment]
Kan ik je helpen daarmee ?

**Comment by jghaanstra** [comment]
Pull request that improve my coding are more than welcome ...

**Comment by jghaanstra** [comment]
Although it can still happen that devices are not reachable due to timeout issues it should not happen anymore (or at least not a lot) that the app crashes since release 2.8.3. I'm closing this issue.
